//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bierstrichler.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("640")]
        public double ApplicationWidth {
            get {
                return ((double)(this["ApplicationWidth"]));
            }
            set {
                this["ApplicationWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("480")]
        public double ApplicationHeight {
            get {
                return ((double)(this["ApplicationHeight"]));
            }
            set {
                this["ApplicationHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double ApplicationPosX {
            get {
                return ((double)(this["ApplicationPosX"]));
            }
            set {
                this["ApplicationPosX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double ApplicationPosY {
            get {
                return ((double)(this["ApplicationPosY"]));
            }
            set {
                this["ApplicationPosY"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>data\\images\\items</string>\r\n  <string>data\\images\\persons</string>\r\n</Arra" +
            "yOfString>")]
        public global::System.Collections.Specialized.StringCollection ApplicationDirectories {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ApplicationDirectories"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AutoLoginActive {
            get {
                return ((bool)(this["AutoLoginActive"]));
            }
            set {
                this["AutoLoginActive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.0")]
        public decimal NegativeDepositFactor {
            get {
                return ((decimal)(this["NegativeDepositFactor"]));
            }
            set {
                this["NegativeDepositFactor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00000000-0000-0000-0000-000000000000")]
        public global::System.Guid StandardUser {
            get {
                return ((global::System.Guid)(this["StandardUser"]));
            }
            set {
                this["StandardUser"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public float ItemSize {
            get {
                return ((float)(this["ItemSize"]));
            }
            set {
                this["ItemSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MailServer {
            get {
                return ((string)(this["MailServer"]));
            }
            set {
                this["MailServer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MailPassword {
            get {
                return ((string)(this["MailPassword"]));
            }
            set {
                this["MailPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MailDisplayName {
            get {
                return ((string)(this["MailDisplayName"]));
            }
            set {
                this["MailDisplayName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MailAddress {
            get {
                return ((string)(this["MailAddress"]));
            }
            set {
                this["MailAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MailLoginName {
            get {
                return ((string)(this["MailLoginName"]));
            }
            set {
                this["MailLoginName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PersonListSecureCopy {
            get {
                return ((string)(this["PersonListSecureCopy"]));
            }
            set {
                this["PersonListSecureCopy"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ItemListSecureCopy {
            get {
                return ((string)(this["ItemListSecureCopy"]));
            }
            set {
                this["ItemListSecureCopy"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int QuestionMinClicks {
            get {
                return ((int)(this["QuestionMinClicks"]));
            }
            set {
                this["QuestionMinClicks"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6")]
        public int QuestionMaxClicks {
            get {
                return ((int)(this["QuestionMaxClicks"]));
            }
            set {
                this["QuestionMaxClicks"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool QuestionGameActive {
            get {
                return ((bool)(this["QuestionGameActive"]));
            }
            set {
                this["QuestionGameActive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string WebCamSource {
            get {
                return ((string)(this["WebCamSource"]));
            }
            set {
                this["WebCamSource"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UpdateExport {
            get {
                return ((string)(this["UpdateExport"]));
            }
            set {
                this["UpdateExport"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection LoggedInUsers {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["LoggedInUsers"]));
            }
            set {
                this["LoggedInUsers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:01:00")]
        public global::System.TimeSpan MailSendInterval {
            get {
                return ((global::System.TimeSpan)(this["MailSendInterval"]));
            }
            set {
                this["MailSendInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int MailMaxMailsPerCall {
            get {
                return ((int)(this["MailMaxMailsPerCall"]));
            }
            set {
                this["MailMaxMailsPerCall"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime NextInvoice {
            get {
                return ((global::System.DateTime)(this["NextInvoice"]));
            }
            set {
                this["NextInvoice"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Monthly")]
        public global::Bierstrichler.Data.Enums.InvoicePeriod InvoicePeriod {
            get {
                return ((global::Bierstrichler.Data.Enums.InvoicePeriod)(this["InvoicePeriod"]));
            }
            set {
                this["InvoicePeriod"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Information")]
        public global::Bierstrichler.Data.Global.LogLevel LogLevel {
            get {
                return ((global::Bierstrichler.Data.Global.LogLevel)(this["LogLevel"]));
            }
            set {
                this["LogLevel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2015-08-19")]
        public global::System.DateTime LastInvoice {
            get {
                return ((global::System.DateTime)(this["LastInvoice"]));
            }
            set {
                this["LastInvoice"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime LastCounting {
            get {
                return ((global::System.DateTime)(this["LastCounting"]));
            }
            set {
                this["LastCounting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>email</string>\r\n  <string>counting</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection UserDirectories {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["UserDirectories"]));
            }
            set {
                this["UserDirectories"] = value;
            }
        }
    }
}
